In [1]:
import sys, re, json
sys.path.append('..')  # Adjust the path as per your directory structure

from scripts.constants import *
from scripts.logging_config import *
from scripts.utils import *


import pandas as pd
import geopandas as gpd
from tqdm import tqdm

In [4]:
geo_level = 'LAD22CD'
geo_code = 'E07000008'

In [2]:
 # IN paths
imd_lsoa_bua_boundaries_path = VECTOR_OUT_DIR / "IMD" / "English_IMD_2019_BUA_filtered_boundaries.geojson"
vom_dir = RASTER_IN_DIR / "Defra" / "VOM"
vom_lad_dir = vom_dir / "LADs"
vom_unzipped_dir = vom_dir / "unzipped_tiles"
vom_zipped_dir = vom_dir / "zipped_tiles"

tif_paths = list(vom_unzipped_dir.rglob("*.tif"))
tif_paths_lst = [[path.parent.name, extract_grid_reference(path.name), classify_vom_type(path.name), str(path)] for path in tif_paths]

tif_paths_df = pd.DataFrame(tif_paths_lst, columns=['year', 'TILE_NAME', 'file_type', 'path']).sort_values(['TILE_NAME', 'year']).reset_index(drop=True)

In [15]:
import os

directory_path = '/maps/acz25/phd-thesis-data/output/vector/3-30-300/VOM_Trees/'
files_list = os.listdir(directory_path)
print(files_list)

# Extract code and year from file names and create a dataframe
file_info = []
for file in files_list:
    match = re.match(r'VOM_trees_(\w+)_(\d{4})\.gpkg', file)
    if match:
        code, year = match.groups()
        file_info.append((code, year))

file_info_df = pd.DataFrame(file_info, columns=['Code', 'Year']).sort_values(['Code', 'Year']).reset_index(drop=True)

['VOM_trees_SE0040_2021.gpkg', 'VOM_trees_NZ2575_2018.gpkg', 'VOM_trees_SU5540_2021.gpkg', 'VOM_trees_NZ2570_2021.gpkg', 'VOM_trees_SP6580_2018.gpkg', 'VOM_trees_SD4075_2019.gpkg', 'VOM_trees_SS5005_2022.gpkg', 'VOM_trees_TQ8575_2018.gpkg', 'VOM_trees_ST5525_2021.gpkg', 'VOM_trees_TF2090_2019.gpkg', 'VOM_trees_SO6065_2020.gpkg', 'VOM_trees_SD2565_2021.gpkg', 'VOM_trees_SP0090_2020.gpkg', 'VOM_trees_NY8020_2021.gpkg', 'VOM_trees_SE9090_2022.gpkg', 'VOM_trees_TG2525_2021.gpkg', 'VOM_trees_SP4505_2022.gpkg', 'VOM_trees_SU8000_2019.gpkg', 'VOM_trees_TF4050_2019.gpkg', 'VOM_trees_SK8585_2018.gpkg', 'VOM_trees_TM0540_2023.gpkg', 'VOM_trees_SU5090_2019.gpkg', 'VOM_trees_ST8065_2019.gpkg', 'VOM_trees_SE6080_2021.gpkg', 'VOM_trees_TL2065_2023.gpkg', 'VOM_trees_SE9555_2018.gpkg', 'VOM_trees_SP2010_2023.gpkg', 'VOM_trees_SJ7035_2021.gpkg', 'VOM_trees_TQ1060_2021.gpkg', 'VOM_trees_TQ1075_2023.gpkg', 'VOM_trees_SK3010_2022.gpkg', 'VOM_trees_NY5560_2019.gpkg', 'VOM_trees_NY3560_2020.gpkg', 'VOM_trees_SD9020_2019.gpkg', 'VOM_trees_TQ7060_2018.gpkg', 'VOM_trees_SD9025_2020.gpkg', 'VOM_trees_SX3095_2021.gpkg', 'VOM_trees_SK5015_2022.gpkg', 'VOM_trees_TL4060_2023.gpkg', 'VOM_trees_SP9090_2021.gpkg', 'VOM_trees_NY1025_2019.gpkg', 'VOM_trees_TA0025_2021.gpkg', 'VOM_trees_SE0085_2021.gpkg', 'VOM_trees_SK7545_2019.gpkg', 'VOM_trees_SJ3570_2021.gpkg', 'VOM_trees_TL4075_2021.gpkg', 'VOM_trees_SP0055_2020.gpkg', 'VOM_trees_SO9570_2020.gpkg', 'VOM_trees_TF2055_2019.gpkg', 'VOM_trees_SW4535_2020.gpkg', 'VOM_trees_SP2500_2022.gpkg', 'VOM_trees_TG4520_2021.gpkg', 'VOM_trees_TF0515_2019.gpkg', 'VOM_trees_SJ7520_2019.gpkg', 'VOM_trees_SU5055_2019.gpkg', 'VOM_trees_TF4095_2019.gpkg', 'VOM_trees_SD4560_2021.gpkg', 'VOM_trees_TM0590_2021.gpkg', 'VOM_trees_SD6025_2018.gpkg', 'VOM_trees_NT8530_2018.gpkg', 'VOM_trees_TF9015_2022.gpkg', 'VOM_trees_TL9525_2022.gpkg', 'VOM_trees_SU7515_2019.gpkg', 'VOM_trees_SJ8520_2021.gpkg', 'VOM_trees_SE4505_2021.gpkg', 'VOM_trees_NZ6020_2023.gpkg', 'VOM_trees_SW9065_2023.gpkg', 'VOM_trees_NY8535_2019.gpkg', 'VOM_trees_SO6575_2021.gpkg', 'VOM_trees_ST7570_2019.gpkg', 'VOM_trees_ST7575_2020.gpkg', 'VOM_trees_SS3000_2022.gpkg', 'VOM_trees_SU3545_2021.gpkg', 'VOM_trees_SP9070_2020.gpkg', 'VOM_trees_SJ3595_2019.gpkg', 'VOM_trees_SD4055_2021.gpkg', 'VOM_trees_TL4090_2019.gpkg', 'VOM_trees_SU5560_2019.gpkg', 'VOM_trees_SY8595_2021.gpkg', 'VOM_trees_TL9010_2022.gpkg', 'VOM_trees_TF9520_2022.gpkg', 'VOM_trees_NT8000_2021.gpkg', 'VOM_trees_TQ8555_2020.gpkg', 'VOM_trees_TQ1585_2023.gpkg', 'VOM_trees_NZ6515_2023.gpkg', 'VOM_trees_ST5500_2020.gpkg', 'VOM_trees_SU3070_2021.gpkg', 'VOM_trees_ST8590_2020.gpkg', 'VOM_trees_NZ4040_2021.gpkg', 'VOM_trees_SJ5085_2021.gpkg', 'VOM_trees_SO9590_2021.gpkg', 'VOM_trees_SE6570_2021.gpkg', 'VOM_trees_SK5520_2022.gpkg', 'VOM_trees_TQ8085_2018.gpkg', 'VOM_trees_TF6535_2018.gpkg', 'VOM_trees_NY3055_2020.gpkg', 'VOM_trees_SD9515_2019.gpkg', 'VOM_trees_SP6070_2018.gpkg', 'VOM_trees_SD4585_2019.gpkg', 'VOM_trees_NY1510_2019.gpkg', 'VOM_trees_NZ2085_2018.gpkg', 'VOM_trees_TL4555_2023.gpkg', 'VOM_trees_SK7060_2022.gpkg', 'VOM_trees_NY7000_2021.gpkg', 'VOM_trees_SO9040_2019.gpkg', 'VOM_trees_SP0560_2020.gpkg', 'VOM_trees_TQ3500_2019.gpkg', 'VOM_trees_TR0095_2018.gpkg', 'VOM_trees_ST8040_2018.gpkg', 'VOM_trees_TF0020_2019.gpkg', 'VOM_trees_SJ7015_2019.gpkg', 'VOM_trees_TG4015_2021.gpkg', 'VOM_trees_NY5540_2021.gpkg', 'VOM_trees_SY7080_2021.gpkg', 'VOM_trees_TL6505_2022.gpkg', 'VOM_trees_TA2540_2020.gpkg', 'VOM_trees_SU8530_2020.gpkg', 'VOM_trees_TG2010_2021.gpkg', 'VOM_trees_SK7560_2018.gpkg', 'VOM_trees_TQ5505_2019.gpkg', 'VOM_trees_TA0000_2020.gpkg', 'VOM_trees_TF4565_2019.gpkg', 'VOM_trees_SE9060_2018.gpkg', 'VOM_trees_SJ5040_2021.gpkg', 'VOM_trees_SD2580_2019.gpkg', 'VOM_trees_SK1070_2020.gpkg', 'VOM_trees_TL2550_2023.gpkg', 'VOM_trees_SO6085_2021.gpkg', 'VOM_trees_ST8550_2019.gpkg', 'VOM_trees_NY5055_2019.gpkg', 'VOM_trees_SW6045_2023.gpkg', 'VOM_trees_SK3525_2022.gpkg', 'VOM_trees_TL0005_2021.gpkg', 'VOM_trees_TQ1555_2021.gpkg', 'VOM_trees_SY1590_2019.gpkg', 'VOM_trees_TL4585_2021.gpkg', 'VOM_trees_ST1040_2019.gpkg', 'VOM_trees_SS5525_2020.gpkg', 'VOM_trees_SE0575_2021.gpkg', 'VOM_trees_SE2035_2021.gpkg', 'VOM_trees_TQ7590_2018.gpkg', 'VOM_trees_NZ0500_2018.gpkg', 'VOM_trees_SU7535_2021.gpkg', 'VOM_trees_SD6010_2022.gpkg', 'VOM_trees_SJ8500_2019.gpkg', 'VOM_trees_SU1025_2019.gpkg', 'VOM_trees_SE4525_2019.gpkg', 'VOM_trees_NY8515_2021.gpkg', 'VOM_trees_TL2095_2019.gpkg', 'VOM_trees_SO6550_2020.gpkg', 'VOM_trees_SJ6015_2019.gpkg', 'VOM_trees_TF1020_2019.gpkg', 'VOM_trees_TG5015_2021.gpkg', 'VOM_trees_SP3025_2019.gpkg', 'VOM_trees_SK2020_2021.gpkg', 'VOM_trees_NY6000_2021.gpkg', 'VOM_trees_SO8040_2019.gpkg', 'VOM_trees_ST9040_2018.gpkg', 'VOM_trees_SP1560_2020.gpkg', 'VOM_trees_TQ2500_2019.gpkg', 'VOM_trees_ST6590_2018.gpkg', 'VOM_trees_TF3560_2019.gpkg', 'VOM_trees_SP7070_2018.gpkg', 'VOM_trees_TL5555_2023.gpkg', 'VOM_trees_SK6060_2022.gpkg', 'VOM_trees_NZ3085_2018.gpkg', 'VOM_trees_NY0510_2019.gpkg', 'VOM_trees_TQ6555_2018.gpkg', 'VOM_trees_TF7535_2018.gpkg', 'VOM_trees_SK4520_2022.gpkg', 'VOM_trees_TQ9085_2018.gpkg', 'VOM_trees_SD8515_2019.gpkg', 'VOM_trees_NY2055_2020.gpkg', 'VOM_trees_NU2030_2018.gpkg', 'VOM_trees_SP5520_2023.gpkg', 'VOM_trees_TM3030_2020.gpkg', 'VOM_trees_ST9590_2020.gpkg', 'VOM_trees_NY9000_2019.gpkg', 'VOM_trees_SO8590_2021.gpkg', 'VOM_trees_SW8550_2023.gpkg', 'VOM_trees_TQ0585_2023.gpkg', 'VOM_trees_SO5505_2018.gpkg', 'VOM_trees_NT9000_2021.gpkg', 'VOM_trees_TF8520_2022.gpkg', 'VOM_trees_SY9595_2021.gpkg', 'VOM_trees_TL8010_2022.gpkg', 'VOM_trees_TQ9555_2020.gpkg', 'VOM_trees_SP8070_2020.gpkg', 'VOM_trees_SK9075_2018.gpkg', 'VOM_trees_SD5055_2021.gpkg', 'VOM_trees_SJ4590_2019.gpkg', 'VOM_trees_SO7550_2020.gpkg', 'VOM_trees_SU2575_2022.gpkg', 'VOM_trees_TL3095_2019.gpkg', 'VOM_trees_SU0025_2019.gpkg', 'VOM_trees_SE5520_2020.gpkg', 'VOM_trees_SJ9500_2019.gpkg', 'VOM_trees_SX4070_2020.gpkg', 'VOM_trees_NZ1500_2018.gpkg', 'VOM_trees_SD7010_2022.gpkg', 'VOM_trees_SU6535_2021.gpkg', 'VOM_trees_NZ3045_2021.gpkg', 'VOM_trees_SU4075_2021.gpkg', 'VOM_trees_SE1575_2021.gpkg', 'VOM_trees_TL5580_2018.gpkg', 'VOM_trees_SS4525_2020.gpkg', 'VOM_trees_ST0040_2019.gpkg', 'VOM_trees_SK2525_2022.gpkg', 'VOM_trees_SW7045_2023.gpkg', 'VOM_trees_SY0590_2019.gpkg', 'VOM_trees_TL1005_2021.gpkg', 'VOM_trees_NY4050_2020.gpkg', 'VOM_trees_SK0070_2020.gpkg', 'VOM_trees_SJ4040_2021.gpkg', 'VOM_trees_SE8060_2018.gpkg', 'VOM_trees_SD3580_2019.gpkg', 'VOM_trees_ST9550_2019.gpkg', 'VOM_trees_SO7085_2021.gpkg', 'VOM_trees_TL3550_2023.gpkg', 'VOM_trees_TF5565_2019.gpkg', 'VOM_trees_TA1000_2020.gpkg', 'VOM_trees_SP7565_2020.gpkg', 'VOM_trees_TQ4505_2019.gpkg', 'VOM_trees_SY6080_2021.gpkg', 'VOM_trees_TL7505_2022.gpkg', 'VOM_trees_TG3010_2021.gpkg', 'VOM_trees_SU9530_2020.gpkg', 'VOM_trees_NY4565_2020.gpkg', 'VOM_trees_SJ6035_2021.gpkg', 'VOM_trees_SX4090_2021.gpkg', 'VOM_trees_TQ0075_2023.gpkg', 'VOM_trees_TL3065_2023.gpkg', 'VOM_trees_SW5030_2023.gpkg', 'VOM_trees_SE7080_2021.gpkg', 'VOM_trees_ST9065_2019.gpkg', 'VOM_trees_SE8555_2018.gpkg', 'VOM_trees_TM1540_2023.gpkg', 'VOM_trees_SK9585_2018.gpkg', 'VOM_trees_TF5050_2019.gpkg', 'VOM_trees_SW3530_2020.gpkg', 'VOM_trees_TG3525_2021.gpkg', 'VOM_trees_SU9000_2019.gpkg', 'VOM_trees_TF7500_2022.gpkg', 'VOM_trees_SP5510_2020.gpkg', 'VOM_trees_SU2050_2019.gpkg', 'VOM_trees_SS2505_2021.gpkg', 'VOM_trees_SP1090_2020.gpkg', 'VOM_trees_SO7065_2020.gpkg', 'VOM_trees_TF3090_2019.gpkg', 'VOM_trees_SK0090_2021.gpkg', 'VOM_trees_SE8090_2022.gpkg', 'VOM_trees_ST4525_2021.gpkg', 'VOM_trees_SE5015_2020.gpkg', 'VOM_trees_SX4545_2020.gpkg', 'VOM_trees_SX2055_2018.gpkg', 'VOM_trees_SE3500_2021.gpkg', 'VOM_trees_ST2035_2019.gpkg', 'VOM_trees_SD7530_2020.gpkg', 'VOM_trees_SK6590_2022.gpkg', 'VOM_trees_SE1040_2021.gpkg', 'VOM_trees_SP7585_2021.gpkg', 'VOM_trees_NZ3575_2018.gpkg', 'VOM_trees_NZ3570_2021.gpkg', 'VOM_trees_SU4540_2021.gpkg', 'VOM_trees_NY9535_2019.gpkg', 'VOM_trees_SO7575_2021.gpkg', 'VOM_trees_ST6570_2019.gpkg', 'VOM_trees_SU2545_2021.gpkg', 'VOM_trees_SS2000_2022.gpkg', 'VOM_trees_SJ9520_2021.gpkg', 'VOM_trees_NZ7020_2023.gpkg', 'VOM_trees_SU6510_2020.gpkg', 'VOM_trees_SD7025_2018.gpkg', 'VOM_trees_NT9530_2018.gpkg', 'VOM_trees_TL8525_2022.gpkg', 'VOM_trees_SY6570_2021.gpkg', 'VOM_trees_TF8015_2022.gpkg', 'VOM_trees_SD5560_2021.gpkg', 'VOM_trees_SS4500_2021.gpkg', 'VOM_trees_TM1590_2021.gpkg', 'VOM_trees_SP3500_2022.gpkg', 'VOM_trees_SJ6520_2019.gpkg', 'VOM_trees_TF1515_2019.gpkg', 'VOM_trees_TF3055_2019.gpkg', 'VOM_trees_SO8570_2020.gpkg', 'VOM_trees_SP1055_2020.gpkg', 'VOM_trees_NY6535_2021.gpkg', 'VOM_trees_SE1085_2021.gpkg', 'VOM_trees_SP7540_2021.gpkg', 'VOM_trees_NY0025_2019.gpkg', 'VOM_trees_TA1025_2021.gpkg', 'VOM_trees_TL5060_2023.gpkg', 'VOM_trees_SK6555_2022.gpkg', 'VOM_trees_SP8090_2021.gpkg', 'VOM_trees_TQ4525_2021.gpkg', 'VOM_trees_SU4585_2021.gpkg', 'VOM_trees_NU0045_2018.gpkg', 'VOM_trees_SJ2570_2021.gpkg', 'VOM_trees_SP5015_2023.gpkg', 'VOM_trees_NU2505_2018.gpkg', 'VOM_trees_SD8020_2019.gpkg', 'VOM_trees_NY2560_2020.gpkg', 'VOM_trees_TF7000_2018.gpkg', 'VOM_trees_SK4015_2022.gpkg', 'VOM_trees_SD8025_2020.gpkg', 'VOM_trees_TQ6060_2018.gpkg', 'VOM_trees_TA3000_2020.gpkg', 'VOM_trees_TQ6505_2019.gpkg', 'VOM_trees_SO3590_2020.gpkg', 'VOM_trees_TG1010_2021.gpkg', 'VOM_trees_TL5505_2022.gpkg', 'VOM_trees_TM1535_2023.gpkg', 'VOM_trees_NY9580_2020.gpkg', 'VOM_trees_SE8520_2018.gpkg', 'VOM_trees_SY2590_2019.gpkg', 'VOM_trees_TQ2550_2018.gpkg', 'VOM_trees_NY6055_2019.gpkg', 'VOM_trees_SK0525_2022.gpkg', 'VOM_trees_SE8525_2021.gpkg', 'VOM_trees_SO5085_2021.gpkg', 'VOM_trees_TL1550_2023.gpkg', 'VOM_trees_SD1580_2019.gpkg', 'VOM_trees_SJ6040_2021.gpkg', 'VOM_trees_SK2070_2020.gpkg', 'VOM_trees_SD5010_2022.gpkg', 'VOM_trees_SX0560_2018.gpkg', 'VOM_trees_SU4535_2021.gpkg', 'VOM_trees_ST0505_2020.gpkg', 'VOM_trees_SK9020_2020.gpkg', 'VOM_trees_SE1035_2021.gpkg', 'VOM_trees_SP8020_2021.gpkg', 'VOM_trees_SK9025_2019.gpkg', 'VOM_trees_NZ3510_2023.gpkg', 'VOM_trees_ST2040_2019.gpkg', 'VOM_trees_SZ5580_2021.gpkg', 'VOM_trees_SD7545_2020.gpkg', 'VOM_trees_TL7580_2018.gpkg', 'VOM_trees_SS6525_2020.gpkg', 'VOM_trees_SU0565_2019.gpkg', 'VOM_trees_TL1095_2019.gpkg', 'VOM_trees_SO5550_2020.gpkg', 'VOM_trees_ST4550_2021.gpkg', 'VOM_trees_SD3505_2023.gpkg', 'VOM_trees_SU2025_2019.gpkg', 'VOM_trees_TQ4085_2020.gpkg', 'VOM_trees_SU6560_2019.gpkg', 'VOM_trees_NX9525_2019.gpkg', 'VOM_trees_SD8585_2021.gpkg', 'VOM_trees_TQ9015_2020.gpkg', 'VOM_trees_NT9545_2018.gpkg', 'VOM_trees_ST2555_2021.gpkg', 'VOM_trees_SE5570_2021.gpkg', 'VOM_trees_SZ3585_2021.gpkg', 'VOM_trees_SJ6085_2021.gpkg', 'VOM_trees_ST6500_2020.gpkg', 'VOM_trees_SU2530_2021.gpkg', 'VOM_trees_NY9540_2019.gpkg', 'VOM_trees_NZ5515_2023.gpkg', 'VOM_trees_NZ1085_2018.gpkg', 'VOM_trees_SU9575_2023.gpkg', 'VOM_trees_TL8095_2018.gpkg', 'VOM_trees_SK4060_2022.gpkg', 'VOM_trees_TL7555_2023.gpkg', 'VOM_trees_SP5070_2018.gpkg', 'VOM_trees_SS9025_2022.gpkg', 'VOM_trees_SY4595_2019.gpkg', 'VOM_trees_TA1055_2018.gpkg', 'VOM_trees_SK6520_2022.gpkg', 'VOM_trees_SP7535_2021.gpkg', 'VOM_trees_TQ4555_2018.gpkg', 'VOM_trees_SO8500_2019.gpkg', 'VOM_trees_NY6540_2021.gpkg', 'VOM_trees_SK0020_2021.gpkg', 'VOM_trees_SJ4010_2020.gpkg', 'VOM_trees_TF3025_2020.gpkg', 'VOM_trees_ST9500_2018.gpkg', 'VOM_trees_TL3510_2019.gpkg', 'VOM_trees_TF1560_2019.gpkg', 'VOM_trees_TQ0500_2019.gpkg', 'VOM_trees_TM5070_2023.gpkg', 'VOM_trees_NY4000_2021.gpkg', 'VOM_trees_SJ9080_2020.gpkg', 'VOM_trees_TM3045_2020.gpkg', 'VOM_trees_SS9510_2022.gpkg', 'VOM_trees_TF7540_2018.gpkg', 'VOM_trees_SK4555_2022.gpkg', 'VOM_trees_TL7060_2023.gpkg', 'VOM_trees_NY2025_2019.gpkg', 'VOM_trees_TQ4060_2018.gpkg', 'VOM_trees_TF5000_2018.gpkg', 'VOM_trees_SK6015_2022.gpkg', 'VOM_trees_TA1560_2018.gpkg', 'VOM_trees_SP7015_2023.gpkg', 'VOM_trees_NU0505_2018.gpkg', 'VOM_trees_SX9050_2020.gpkg', 'VOM_trees_ST9035_2018.gpkg', 'VOM_trees_TL3025_2019.gpkg', 'VOM_trees_SJ4525_2020.gpkg', 'VOM_trees_TF3510_2020.gpkg', 'VOM_trees_SO8035_2019.gpkg', 'VOM_trees_SK0515_2021.gpkg', 'VOM_trees_TF1055_2019.gpkg', 'VOM_trees_SP8005_2020.gpkg', 'VOM_trees_SD5025_2018.gpkg', 'VOM_trees_SU4510_2020.gpkg', 'VOM_trees_TQ9520_2020.gpkg', 'VOM_trees_NX9010_2019.gpkg', 'VOM_trees_SU6055_2019.gpkg', 'VOM_trees_SO3060_2020.gpkg', 'VOM_trees_SU0545_2021.gpkg', 'VOM_trees_SO5575_2021.gpkg', 'VOM_trees_TM5090_2022.gpkg', 'VOM_trees_SP3580_2021.gpkg', 'VOM_trees_SE7505_2021.gpkg', 'VOM_trees_NZ5020_2023.gpkg', 'VOM_trees_NZ5035_2021.gpkg', 'VOM_trees_ST0035_2019.gpkg', 'VOM_trees_SP8515_2021.gpkg', 'VOM_trees_NZ3035_2018.gpkg', 'VOM_trees_SK9515_2020.gpkg', 'VOM_trees_SX0045_2023.gpkg', 'VOM_trees_SX0055_2018.gpkg', 'VOM_trees_NZ3030_2021.gpkg', 'VOM_trees_SP5580_2018.gpkg', 'VOM_trees_SU6540_2021.gpkg', 'VOM_trees_SS6005_2022.gpkg', 'VOM_trees_TM3095_2022.gpkg', 'VOM_trees_NZ1575_2018.gpkg', 'VOM_trees_SU9085_2023.gpkg', 'VOM_trees_SK4590_2022.gpkg', 'VOM_trees_ST4065_2021.gpkg', 'VOM_trees_SK2090_2021.gpkg', 'VOM_trees_SJ9570_2020.gpkg', 'VOM_trees_SD1565_2021.gpkg', 'VOM_trees_TF1090_2019.gpkg', 'VOM_trees_SO5065_2020.gpkg', 'VOM_trees_SU0050_2019.gpkg', 'VOM_trees_TR1025_2018.gpkg', 'VOM_trees_SE7015_2020.gpkg', 'VOM_trees_SX9095_2020.gpkg', 'VOM_trees_SU2515_2020.gpkg', 'VOM_trees_ST6525_2021.gpkg', 'VOM_trees_SO7520_2019.gpkg', 'VOM_trees_SU9545_2020.gpkg', 'VOM_trees_SE3590_2019.gpkg', 'VOM_trees_SU6090_2019.gpkg', 'VOM_trees_SD8075_2021.gpkg', 'VOM_trees_TA1075_2020.gpkg', 'VOM_trees_SX0580_2019.gpkg', 'VOM_trees_TQ4575_2020.gpkg', 'VOM_trees_SP7515_2019.gpkg', 'VOM_trees_SJ2520_2020.gpkg', 'VOM_trees_TQ2075_2023.gpkg', 'VOM_trees_SE8010_2021.gpkg', 'VOM_trees_SX6090_2021.gpkg', 'VOM_trees_NY6560_2019.gpkg', 'VOM_trees_SP1010_2023.gpkg', 'VOM_trees_SE5080_2021.gpkg', 'VOM_trees_SW7030_2023.gpkg', 'VOM_trees_SK2550_2022.gpkg', 'VOM_trees_TL1065_2023.gpkg', 'VOM_trees_NZ4020_2023.gpkg', 'VOM_trees_SX8585_2021.gpkg', 'VOM_trees_NZ4035_2021.gpkg', 'VOM_trees_SU1545_2021.gpkg', 'VOM_trees_SP2580_2021.gpkg', 'VOM_trees_TM4090_2022.gpkg', 'VOM_trees_ST5570_2019.gpkg', 'VOM_trees_ST3060_2021.gpkg', 'VOM_trees_TQ8520_2020.gpkg', 'VOM_trees_SD6560_2021.gpkg', 'VOM_trees_SU7055_2019.gpkg', 'VOM_trees_SP9005_2020.gpkg', 'VOM_trees_SU5510_2020.gpkg', 'VOM_trees_SE4595_2019.gpkg', 'VOM_trees_NY5535_2021.gpkg', 'VOM_trees_TF0055_2019.gpkg', 'VOM_trees_SP2055_2020.gpkg', 'VOM_trees_ST8035_2018.gpkg', 'VOM_trees_SX8050_2020.gpkg', 'VOM_trees_SJ5520_2019.gpkg', 'VOM_trees_SK1515_2021.gpkg', 'VOM_trees_SO9035_2019.gpkg', 'VOM_trees_TF2510_2020.gpkg', 'VOM_trees_SK7015_2022.gpkg', 'VOM_trees_TQ5060_2018.gpkg', 'VOM_trees_SP6015_2023.gpkg', 'VOM_trees_NU1505_2018.gpkg', 'VOM_trees_NY1560_2020.gpkg', 'VOM_trees_TA0560_2018.gpkg', 'VOM_trees_SS8510_2022.gpkg', 'VOM_trees_TA2025_2021.gpkg', 'VOM_trees_SE2085_2021.gpkg', 'VOM_trees_SK5555_2022.gpkg', 'VOM_trees_TL6060_2023.gpkg', 'VOM_trees_TF6540_2018.gpkg', 'VOM_trees_SU7590_2023.gpkg', 'VOM_trees_SK3550_2022.gpkg', 'VOM_trees_TL0065_2023.gpkg', 'VOM_trees_SW6030_2023.gpkg', 'VOM_trees_TQ3065_2018.gpkg', 'VOM_trees_SX7090_2021.gpkg', 'VOM_trees_SE9010_2021.gpkg', 'VOM_trees_SJ5035_2021.gpkg', 'VOM_trees_SP0010_2023.gpkg', 'VOM_trees_TL4020_2019.gpkg', 'VOM_trees_TA0075_2020.gpkg', 'VOM_trees_TF4515_2020.gpkg', 'VOM_trees_SJ3520_2020.gpkg', 'VOM_trees_SX1580_2019.gpkg', 'VOM_trees_SE2590_2019.gpkg', 'VOM_trees_SU8545_2020.gpkg', 'VOM_trees_SD9075_2021.gpkg', 'VOM_trees_TA2535_2020.gpkg', 'VOM_trees_SU7090_2019.gpkg', 'VOM_trees_ST7520_2018.gpkg', 'VOM_trees_SE6015_2020.gpkg', 'VOM_trees_TR0025_2018.gpkg', 'VOM_trees_SU3515_2020.gpkg', 'VOM_trees_SK3090_2021.gpkg', 'VOM_trees_SJ8570_2020.gpkg', 'VOM_trees_SP2090_2020.gpkg', 'VOM_trees_SS1505_2021.gpkg', 'VOM_trees_SU1050_2019.gpkg', 'VOM_trees_SO4065_2020.gpkg', 'VOM_trees_TF0090_2019.gpkg', 'VOM_trees_SS7005_2022.gpkg', 'VOM_trees_SU7540_2021.gpkg', 'VOM_trees_SK5590_2022.gpkg', 'VOM_trees_SU7555_2023.gpkg', 'VOM_trees_SU8085_2023.gpkg', 'VOM_trees_SE2040_2021.gpkg', 'VOM_trees_SP4585_2021.gpkg', 'VOM_trees_NZ0575_2018.gpkg', 'VOM_trees_ST1035_2019.gpkg', 'VOM_trees_SX1055_2018.gpkg', 'VOM_trees_SK8515_2020.gpkg', 'VOM_trees_SD2505_2023.gpkg', 'VOM_trees_TQ3080_2020.gpkg', 'VOM_trees_SU3020_2020.gpkg', 'VOM_trees_SE6520_2020.gpkg', 'VOM_trees_TL0095_2019.gpkg', 'VOM_trees_SU1565_2019.gpkg', 'VOM_trees_SJ7595_2020.gpkg', 'VOM_trees_TL6580_2018.gpkg', 'VOM_trees_SZ4580_2021.gpkg', 'VOM_trees_SK8020_2020.gpkg', 'VOM_trees_ST1505_2020.gpkg', 'VOM_trees_SU5535_2021.gpkg', 'VOM_trees_SX1560_2018.gpkg', 'VOM_trees_SK8025_2019.gpkg', 'VOM_trees_NZ2510_2023.gpkg', 'VOM_trees_SE0035_2021.gpkg', 'VOM_trees_SK3065_2022.gpkg', 'VOM_trees_TL0550_2023.gpkg', 'VOM_trees_SW6510_2021.gpkg', 'VOM_trees_SJ7040_2021.gpkg', 'VOM_trees_SY3590_2019.gpkg', 'VOM_trees_SE9520_2018.gpkg', 'VOM_trees_NY8580_2020.gpkg', 'VOM_trees_TL2005_2021.gpkg', 'VOM_trees_SX8075_2021.gpkg', 'VOM_trees_SK1525_2022.gpkg', 'VOM_trees_SE9525_2021.gpkg', 'VOM_trees_NY7055_2019.gpkg', 'VOM_trees_TQ3550_2018.gpkg', 'VOM_trees_TG0010_2021.gpkg', 'VOM_trees_TF4020_2020.gpkg', 'VOM_trees_SJ3015_2020.gpkg', 'VOM_trees_TL4515_2019.gpkg', 'VOM_trees_TM0535_2023.gpkg', 'VOM_trees_SO2590_2020.gpkg', 'VOM_trees_TA2000_2020.gpkg', 'VOM_trees_SU8070_2020.gpkg', 'VOM_trees_NY3005_2021.gpkg', 'VOM_trees_TQ1500_2019.gpkg', 'VOM_trees_TM4070_2023.gpkg', 'VOM_trees_SO4595_2020.gpkg', 'VOM_trees_TF0560_2019.gpkg', 'VOM_trees_ST5590_2018.gpkg', 'VOM_trees_SJ8080_2020.gpkg', 'VOM_trees_NY5000_2021.gpkg', 'VOM_trees_SJ7550_2020.gpkg', 'VOM_trees_SW4540_2020.gpkg', 'VOM_trees_SK1020_2021.gpkg', 'VOM_trees_SO9500_2019.gpkg', 'VOM_trees_TF2020_2019.gpkg', 'VOM_trees_SX8565_2020.gpkg', 'VOM_trees_SJ5015_2019.gpkg', 'VOM_trees_TL2510_2019.gpkg', 'VOM_trees_ST8500_2018.gpkg', 'VOM_trees_TA0055_2018.gpkg', 'VOM_trees_NY1055_2020.gpkg', 'VOM_trees_NU1030_2018.gpkg', 'VOM_trees_SP6520_2023.gpkg', 'VOM_trees_TQ5555_2018.gpkg', 'VOM_trees_SK7530_2019.gpkg', 'VOM_trees_SK5060_2022.gpkg', 'VOM_trees_TL9095_2018.gpkg', 'VOM_trees_TL6555_2023.gpkg', 'VOM_trees_SU8575_2023.gpkg', 'VOM_trees_NZ0085_2018.gpkg', 'VOM_trees_SP4075_2021.gpkg', 'VOM_trees_SP4070_2018.gpkg', 'VOM_trees_SU3530_2021.gpkg', 'VOM_trees_SO6505_2018.gpkg', 'VOM_trees_NZ4515_2023.gpkg', 'VOM_trees_NY8540_2019.gpkg', 'VOM_trees_SE4570_2021.gpkg', 'VOM_trees_SJ7085_2021.gpkg', 'VOM_trees_SD9585_2021.gpkg', 'VOM_trees_SD6055_2021.gpkg', 'VOM_trees_ST3555_2021.gpkg', 'VOM_trees_TQ8015_2020.gpkg', 'VOM_trees_NT8545_2018.gpkg', 'VOM_trees_SD4500_2023.gpkg', 'VOM_trees_TA0585_2020.gpkg', 'VOM_trees_TL1025_2020.gpkg', 'VOM_trees_SP3505_2022.gpkg', 'VOM_trees_TF1510_2019.gpkg', 'VOM_trees_TF3050_2019.gpkg', 'VOM_trees_SP1050_2020.gpkg', 'VOM_trees_SE7580_2022.gpkg', 'VOM_trees_NY6530_2021.gpkg', 'VOM_trees_SE1080_2021.gpkg', 'VOM_trees_SP7545_2021.gpkg', 'VOM_trees_TL5075_2018.gpkg', 'VOM_trees_TA1020_2021.gpkg', 'VOM_trees_NY0020_2019.gpkg', 'VOM_trees_TL5065_2023.gpkg', 'VOM_trees_SK6550_2022.gpkg', 'VOM_trees_SP8095_2021.gpkg', 'VOM_trees_SU4580_2021.gpkg', 'VOM_trees_NU0040_2018.gpkg', 'VOM_trees_NU2500_2018.gpkg', 'VOM_trees_SP5010_2023.gpkg', 'VOM_trees_TF7005_2018.gpkg', 'VOM_trees_SK4010_2022.gpkg', 'VOM_trees_TQ6065_2018.gpkg', 'VOM_trees_NY9530_2019.gpkg', 'VOM_trees_SE8585_2023.gpkg', 'VOM_trees_SU2540_2021.gpkg', 'VOM_trees_SD3075_2019.gpkg', 'VOM_trees_SJ9525_2021.gpkg', 'VOM_trees_SW8060_2023.gpkg', 'VOM_trees_SU6515_2020.gpkg', 'VOM_trees_NT9535_2018.gpkg', 'VOM_trees_ST2525_2021.gpkg', 'VOM_trees_TL8520_2022.gpkg', 'VOM_trees_SY6575_2021.gpkg', 'VOM_trees_TF8010_2022.gpkg', 'VOM_trees_SD5565_2021.gpkg', 'VOM_trees_SS4505_2021.gpkg', 'VOM_trees_TM1595_2021.gpkg', 'VOM_trees_SU2055_2019.gpkg', 'VOM_trees_SP1095_2020.gpkg', 'VOM_trees_SD3560_2021.gpkg', 'VOM_trees_SO7060_2020.gpkg', 'VOM_trees_TF3095_2019.gpkg', 'VOM_trees_SK0095_2021.gpkg', 'VOM_trees_NY9025_2021.gpkg', 'VOM_trees_SO5525_2019.gpkg', 'VOM_trees_SE5010_2020.gpkg', 'VOM_trees_SX2050_2018.gpkg', 'VOM_trees_SE3505_2021.gpkg', 'VOM_trees_ST2030_2019.gpkg', 'VOM_trees_SD7535_2

In [31]:
import os
import re
import pandas as pd

# Define the directory path
directory_path = '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/'
# Search recursively for files in the directory
files_list = []
for root, dirs, files in os.walk(directory_path):
    for file in files:
        files_list.append(os.path.join(root, file))


# Extract code and year from file names and create a dataframe
file_info = []
clean_files = []
for file in files_list:
    if 'VOM_HS' not in file:
        if '.tfw' not in file:
            match = re.match(r'.*/VOM_(\w+)_P_\d+_(\d{4})\d{4}_\d{8}\.tif', file)
            if match:
                code, year = match.groups()
                print(f"Code: {code}, Year: {year}")
                file_info.append((code, year))
                clean_files.append(file)

file_info_df = pd.DataFrame(file_info, columns=['Code', 'Year']).sort_values(['Code', 'Year']).reset_index(drop=True)
file_info_df

Code: SK4550, Year: 2022
Code: TL9035, Year: 2022
Code: TG1025, Year: 2022
Code: SD6005, Year: 2021
Code: SK5020, Year: 2022
Code: TL9525, Year: 2022
Code: SK6050, Year: 2022
Code: TG1535, Year: 2022
Code: SD6515, Year: 2021
Code: SE7580, Year: 2022
Code: NZ1565, Year: 2021
Code: TF8520, Year: 2022
Code: SS7515, Year: 2022
Code: NZ2060, Year: 2021
Code: TG0540, Year: 2022
Code: SK5555, Year: 2022
Code: TG2030, Year: 2022
Code: SD5010, Year: 2021
Code: SK4080, Year: 2022
Code: SD5500, Year: 2021
Code: SK4590, Year: 2022
Code: TM2580, Year: 2022
Code: TL8040, Year: 2022
Code: TF9020, Year: 2022
Code: NZ0065, Year: 2021
Code: SD7560, Year: 2022
Code: TL8025, Year: 2022
Code: SP4500, Year: 2022
Code: TG0035, Year: 2022
Code: SD7015, Year: 2021
Code: TL8535, Year: 2022
Code: SP4010, Year: 2022
Code: TG0525, Year: 2022
Code: TM3080, Year: 2022
Code: TL9540, Year: 2022
Code: TM3590, Year: 2022
Code: TG1040, Year: 2022
Code: SD3530, Year: 2022
Code: SK1025, Year: 2022
Code: SU2585, Year: 2022
Code: SK1535, Year: 2022
Code: TF9005, Year: 2022
Code: SK2030, Year: 2022
Code: SK4025, Year: 2022
Code: SD4530, Year: 2022
Code: SK0540, Year: 2022
Code: SK4500, Year: 2022
Code: SK7065, Year: 2022
Code: SK4010, Year: 2022
Code: TF9515, Year: 2022
Code: NZ0550, Year: 2021
Code: TM0005, Year: 2022
Code: TL7515, Year: 2022
Code: SK4535, Year: 2022
Code: SK0035, Year: 2022
Code: SK5570, Year: 2022
Code: SK6010, Year: 2022
Code: SK4040, Year: 2022
Code: SK5060, Year: 2022
Code: SS3505, Year: 2021
Code: SK6500, Year: 2022
Code: SK0525, Year: 2022
Code: NZ1050, Year: 2021
Code: TF8015, Year: 2022
Code: SD6020, Year: 2021
Code: SK6565, Year: 2022
Code: SD3045, Year: 2022
Code: SK5005, Year: 2022
Code: SK1040, Year: 2022
Code: SK5515, Year: 2022
Code: SX5085, Year: 2022
Code: SK4065, Year: 2022
Code: TF8505, Year: 2022
Code: SP3020, Year: 2022
Code: SK3005, Year: 2022
Code: SK2570, Year: 2022
Code: SS7020, Year: 2021
Code: SK3030, Year: 2022
Code: SK3515, Year: 2022
Code: TM3575, Year: 2022
Code: SD4035, Year: 2022
Code: TL8510, Year: 2022
Code: TL8000, Year: 2022
Code: SK7090, Year: 2022
Code: SK5585, Year: 2022
Code: SK3070, Year: 2022
Code: SS6520, Year: 2021
Code: SK2530, Year: 2022
Code: SK3560, Year: 2022
Code: SP2520, Year: 2022
Code: SD4050, Year: 2022
Code: SK5095, Year: 2022
Code: SK2505, Year: 2022
Code: SK6590, Year: 2022
Code: TL5520, Year: 2021
Code: TF7500, Year: 2022
Code: SK4575, Year: 2022
Code: TL9500, Year: 2022
Code: TL9010, Year: 2022
Code: SK3545, Year: 2022
Code: SE8585, Year: 2022
Code: TL5505, Year: 2021
Code: SS5510, Year: 2021
Code: TM5595, Year: 2022
Code: SS5000, Year: 2021
Code: TM5085, Year: 2022
Code: SS9540, Year: 2022
Code: TL6510, Year: 2021
Code: SS6505, Year: 2021
Code: SS8000, Year: 2022
Code: SK3055, Year: 2022
Code: SS6015, Year: 2021
Code: SS8510, Year: 2022
Code: SP2505, Year: 2022
Code: SK2520, Year: 2022
Code: TL7530, Year: 2022
Code: TM4585, Year: 2022
Code: TM4095, Year: 2022
Code: SE9085, Year: 2022
Code: SP3005, Year: 2022
Code: SK3020, Year: 2022
Code: SS9010, Year: 2022
Code: SS9525, Year: 2022
Code: SS7005, Year: 2021
Code: SS9500, Year: 2022
Code: SK2555, Year: 2022
Code: SS9035, Year: 2022
Code: SP3515, Year: 2022
Code: SK3015, Year: 2022
Code: SK3530, Year: 2022
Code: SK2560, Year: 2022
Code: SP3520, Year: 2022
Code: SK3505, Year: 2022
Code: SD4025, Year: 2022
Code: TL8500, Year: 2022
Code: TL8010, Year: 2022
Code: SK2545, Year: 2022
Code: TM3075, Year: 2022
Code: SK7080, Year: 2022
Code: SK5595, Year: 2022
Code: SK3060, Year: 2022
Code: SK3570, Year: 2022
Code: SS6020, Year: 2021
Code: SD4040, Year: 2022
Code: SK5085, Year: 2022
Code: SK2515, Year: 2022
Code: TM2575, Year: 2022
Code: SK6580, Year: 2022
Code: TF7510, Year: 2022
Code: TL9510, Year: 2022
Code: SK4075, Year: 2022
Code: TL9000, Year: 2022
Code: SS9040, Year: 2022
Code: TL5515, Year: 2021
Code: SS5500, Year: 2021
Code: SS5010, Year: 2021
Code: TM5095, Year: 2022
Code: SE8085, Year: 2022
Code: SS6515, Year: 2021
Code: SS8010, Year: 2022
Code: SS6005, Year: 2021
Code: SK3555, Year: 2022
Code: SS8500, Year: 2022
Code: TL7545, Year: 2022
Code: SP2515, Year: 2022
Code: TL6010, Year: 2021
Code: SE9585, Year: 2022
Code: TM4595, Year: 2022
Code: TM4085, Year: 2022
Code: SP3015, Year: 2022
Code: SS9000, Year: 2022
Code: SS9535, Year: 2022
Code: SS7015, Year: 2021
Code: SS9510, Year: 2022
Code: SS9025, Year: 2022
Code: SP3505, Year: 2022
Code: SK3520, Year: 2022
Code: NZ1065, Year: 2021
Code: TF8020, Year: 2022
Code: TL9025, Year: 2022
Code: SK6550, Year: 2022
Code: SD6015, Year: 2021
Code: TG1035, Year: 2022
Code: TL9535, Year: 2022
Code: SD6505, Year: 2021
Code: TG1525, Year: 2022
Code: SK5520, Year: 2022
Code: SE7590, Year: 2022
Code: SK4050, Year: 2022
Code: SS7505, Year: 2022
Code: NZ2070, Year: 2021
Code: TL8540, Year: 2022
Code: SD5000, Year: 2021
Code: SK4090, Year: 2022
Code: SK5055, Year: 2022
Code: SD5510, Year: 2021
Code: SK4580, Year: 2022
Code: TM2590, Year: 2022
Code: TG0040, Year: 2022
Code: TL8035, Year: 2022
Code: SP4510, Year: 2022
Code: SD7005, Year: 2021
Code: TG0025, Year: 2022
Code: SK7050, Year: 2022
Code: TL8525, Year: 2022
Code: SP4000, Year: 2022
Code: TG0535, Year: 2022
Code: TF9520, Year: 2022
Code: NZ0565, Year: 2021
Code: TL7520, Year: 2022
Code: TM3090, Year: 2022
Code: TG1540, Year: 2022
Code: TM3580, Year: 2022
Code: TL9040, Year: 2022
Code: SK1035, Year: 2022
Code: SK7010, Year: 2022
Code: SU2595, Year: 2022
Code: SD3030, Year: 2022
Code: SK1525, Year: 2022
Code: TF9015, Year: 2022
Code: NZ0050, Year: 2021
Code: SD7555, Year: 2022
Code: SK4035, Year: 2022
Code: SD7020, Year: 2021
Code: SK4510, Year: 2022
Code: SK0040, Year: 2022
Code: SK4000, Year: 2022
Code: TF9505, Year: 2022
Code: TL7505, Year: 2022
Code: SD4030, Year: 2022
Code: SK4525, Year: 2022
Code: NZ2055, Year: 2021
Code: SS7520, Year: 2022
Code: SK0025, Year: 2022
Code: SK4540, Year: 2022
Code: SS3005, Year: 2021
Code: SK5560, Year: 2022
Code: SK6000, Year: 2022
Code: SK2045, Year: 2022
Code: SK5070, Year: 2022
Code: SK6510, Year: 2022
Code: SK0535, Year: 2022
Code: TF8005, Year: 2022
Code: SK4565, Year: 2022
Code: SK1540, Year: 2022
Code: SK5015, Year: 2022
Code: SD6520, Year: 2021
Code: SK6065, Year: 2022
Code: SD3545, Year: 2022
Code: SK5505, Year: 2022
Code: SX5095, Year: 2022
Code: NZ1550, Year: 2021
Code: TF8515, Year: 2022
Code: SE2500, Year: 2022
Code: SP3010, Year: 2022
Code: SS9005, Year: 2022
Code: SS9530, Year: 2022
Code: SS9515, Year: 2022
Code: SS7010, Year: 2021
Code: SP3500, Year: 2022
Code: TL7525, Year: 2022
Code: SE9580, Year: 2022
Code: TM4590, Year: 2022
Code: SU2575, Year: 2022
Code: TL8520, Year: 2022
Code: SD8060, Year: 2022
Code: TM4080, Year: 2022
Code: SE9090, Year: 2022
Code: SX5075, Year: 2022
Code: TL6505, Year: 2021
Code: SS8015, Year: 2022
Code: SS6510, Year: 2021
Code: SK3550, Year: 2022
Code: SS8505, Year: 2022
Code: SS6000, Year: 2021
Code: TL7540, Year: 2022
Code: SP2510, Year: 2022
Code: TL6015, Year: 2021
Code: SS9045, Year: 2022
Code: TL5510, Year: 2021
Code: SE8590, Year: 2022
Code: SS5505, Year: 2021
Code: TM5090, Year: 2022
Code: SS5015, Year: 2021
Code: SD9560, Year: 2022
Code: TL9020, Year: 2022
Code: SE8080, Year: 2022
Code: SK3040, Year: 2022
Code: SK6585, Year: 2022
Code: TF7515, Year: 2022
Code: SS5520, Year: 2021
Code: SD9055, Year: 2022
Code: TL9515, Year: 2022
Code: TL9005, Year: 2022
Code: SK5590, Year: 2022
Code: TL6520, Year: 2021
Code: SK3065, Year: 2022
Code: SK2525, Year: 2022
Code: SS8520, Year: 2022
Code: SK2510, Year: 2022
Code: SD4045, Year: 2022
Code: SK5080, Year: 2022
Code: TL8505, Year: 2022
Code: TL8015, Year: 2022
Code: SD8555, Year: 2022
Code: SK2540, Year: 2022
Code: SK7085, Year: 2022
Code: SK3010, Year: 2022
Code: SS9020, Year: 2022
Code: SK3535, Year: 2022
Code: SK2565, Year: 2022
Code: SK3025, Year: 2022
Code: SK3500, Year: 2022
Code: TF8000, Year: 2022
Code: SK4560, Year: 2022
Code: SK6570, Year: 2022
Code: SK1545, Year: 2022
Code: SK5010, Year: 2022
Code: SK6060, Year: 2022
Code: SK5500, Year: 2022
Code: SD3540, Year: 2022
Code: SE2505, Year: 2022
Code: NZ1555, Year: 2021
Code: SX5090, Year: 2022
Code: SK4070, Year: 2022
Code: TF8510, Year: 2022
Code: NZ2050, Year: 2021
Code: SK5565, Year: 2022
Code: SS3000, Year: 2021
Code: TM5075, Year: 2022
Code: SK4545, Year: 2022
Code: SD5020, Year: 2021
Code: SK6005, Year: 2022
Code: SS3510, Year: 2021
Code: SD4540, Year: 2022
Code: SK2040, Year: 2022
Code: SK6515, Year: 2022
Code: SK0530, Year: 2022
Code: TF9010, Year: 2022
Code: NZ0055, Year: 2021
Code: SK2025, Year: 2022
Code: SK4030, Year: 2022
Code: SK4515, Year: 2022
Code: SK7070, Year: 2022
Code: SK0045, Year: 2022
Code: SP4020, Year: 2022
Code: SK4005, Year: 2022
Code: TF9500, Year: 2022
Code: SD4035, Year: 2022
Code: TL7500, Year: 2022
Code: TM0010, Year: 2022
Code: SD3525, Year: 2022
Code: SK1030, Year: 2022
Code: SK7015, Year: 2022
Code: SS2500, Year: 2021
Code: SU2590, Year: 2022
Code: TM4575, Year: 2022
Code: SD3035, Year: 2022
Code: TM3095, Year: 2022
Code: TM3585, Year: 2022
Code: NZ0070, Year: 2021
Code: SP4515, Year: 2022
Code: SD7000, Year: 2021
Code: TL8030, Year: 2022
Code: SP4005, Year: 2022
Code: TG0530, Year: 2022
Code: SK7055, Year: 2022
Code: SK4020, Year: 2022
Code: NZ0560, Year: 2021
Code: TG2040, Year: 2022
Code: SS7500, Year: 2022
Code: TL8545, Year: 2022
Code: TG2025, Year: 2022
Code: SD5005, Year: 2021
Code: SK4095, Year: 2022
Code: SK6020, Year: 2022
Code: SD5515, Year: 2021
Code: SK5050, Year: 2022
Code: SK4585, Year: 2022
Code: TM2595, Year: 2022
Code: TG0045, Year: 2022
Code: NZ1060, Year: 2021
Code: TG1030, Year: 2022
Code: SD6010, Year: 2021
Code: SK6555, Year: 2022
Code: SD6500, Year: 2021
Code: TL9530, Year: 2022
Code: NZ1570, Year: 2021
Code: SK4055, Year: 2022
Code: SK5575, Year: 2022
Code: NZ1055, Year: 2021
Code: TF8010, Year: 2022
Code: SK4570, Year: 2022
Code: SK6560, Year: 2022
Code: SK5000, Year: 2022
Code: SD3040, Year: 2022
Code: SK6070, Year: 2022
Code: SK1045, Year: 2022
Code: SK5510, Year: 2022
Code: SD3550, Year: 2022
Code: SX5080, Year: 2022
Code: SK4060, Year: 2022
Code: TF8500, Year: 2022
Code: SK0030, Year: 2022
Code: SS3010, Year: 2021
Code: SD4040, Year: 2022
Code: SK6015, Year: 2022
Code: SS3500, Year: 2021
Code: SK5065, Year: 2022
Code: SD5520, Year: 2021
Code: SK4045, Year: 2022
Code: SK6505, Year: 2022
Code: TF9000, Year: 2022
Code: SK2035, Year: 2022
Code: SD4535, Year: 2022
Code: SP4520, Year: 2022
Code: SK0545, Year: 2022
Code: SK4505, Year: 2022
Code: SK7060, Year: 2022
Code: SK4015, Year: 2022
Code: TF9510, Year: 2022
Code: NZ0555, Year: 2021
Code: TL7510, Year: 2022
Code: TM0000, Year: 2022
Code: SK4530, Year: 2022
Code: SD3535, Year: 2022
Code: SS2000, Year: 2021
Code: TM4075, Year: 2022
Code: SK7005, Year: 2022
Code: SU2580, Year: 2022
Code: SD3025, Year: 2022
Code: SK1530, Year: 2022
Code: TM3085, Year: 2022
Code: TL9545, Year: 2022
Code: SK7020, Year: 2022
Code: TM3595, Year: 2022
Code: NZ0060, Year: 2021
Code: SP4505, Year: 2022
Code: SD7010, Year: 2021
Code: TG0030, Year: 2022
Code: SK4520, Year: 2022
Code: SP4015, Year: 2022
Code: TL8530, Year: 2022
Code: NZ0570, Year: 2021
Code: NZ2065, Year: 2021
Code: SS7510, Year: 2022
Code: TG0545, Year: 2022
Code: SD5015, Year: 2021
Code: TG2035, Year: 2022
Code: SK5550, Year: 2022
Code: SK4085, Year: 2022
Code: SD5505, Year: 2021
Code: SK4595, Year: 2022
Code: SK6520, Year: 2022
Code: TM2585, Year: 2022
Code: TL8045, Year: 2022
Code: NZ1070, Year: 2021
Code: SK4555, Year: 2022
Code: SK5075, Year: 2022
Code: SD6000, Year: 2021
Code: TL9030, Year: 2022
Code: SD6510, Year: 2021
Code: TG1530, Year: 2022
Code: SK6055, Year: 2022
Code: SE7585, Year: 2022
Code: NZ1560, Year: 2021
Code: SP3000, Year: 2022
Code: SS9015, Year: 2022
Code: SS9505, Year: 2022
Code: SK2550, Year: 2022
Code: SS7000, Year: 2021
Code: SS9030, Year: 2022
Code: SP3510, Year: 2022
Code: TL7535, Year: 2022
Code: SE9590, Year: 2022
Code: TM4580, Year: 2022
Code: TM4090, Year: 2022
Code: TL8020, Year: 2022
Code: SD8560, Year: 2022
Code: SE9080, Year: 2022
Code: TL6515, Year: 2021
Code: SS8005, Year: 2022
Code: SK3050, Year: 2022
Code: SS6500, Year: 2021
Code: SS8515, Year: 2022
Code: SS6010, Year: 2021
Code: SP2500, Year: 2022
Code: TL6005, Year: 2021
Code: SE8580, Year: 2022
Code: TM5590, Year: 2022
Code: SS5515, Year: 2021
Code: TF7520, Year: 2022
Code: SD9060, Year: 2022
Code: TL9520, Year: 2022
Code: TM5080, Year: 2022
Code: SS5005, Year: 2021
Code: SS9545, Year: 2022
Code: SE8090, Year: 2022
Code: SK6595, Year: 2022
Code: TF7505, Year: 2022
Code: TL9505, Year: 2022
Code: SS5020, Year: 2021
Code: SD9555, Year: 2022
Code: SK3540, Year: 2022
Code: SK5580, Year: 2022
Code: SS8020, Year: 2022
Code: SK2535, Year: 2022
Code: SK3565, Year: 2022
Code: SK2500, Year: 2022
Code: TL6020, Year: 2021
Code: SK5090, Year: 2022
Code: SD4030, Year: 2022
Code: TL8515, Year: 2022
Code: SD8055, Year: 2022
Code: TL8005, Year: 2022
Code: SK7095, Year: 2022
Code: SK3000, Year: 2022
Code: SK3525, Year: 2022
Code: SS9520, Year: 2022
Code: SK3035, Year: 2022
Code: SK3510, Year: 2022
Code: TM1590, Year: 2021
Code: SU4080, Year: 2021
Code: ST6035, Year: 2021
Code: SZ5580, Year: 2020
Code: SD6050, Year: 2020
Code: SK0095, Year: 2021
Code: SE9535, Year: 2021
Code: SO4555, Year: 2021
Code: SK0000, Year: 2021
Code: TQ0055, Year: 2021
Code: SU2560, Year: 2021
Code: SP4575, Year: 2020
Code: SS1500, Year: 2021
Code: SK0510, Year: 2021
Code: SE2065, Year: 2021
Code: NZ3045, Year: 2021
Code: ST4045, Year: 2021
Code: SJ6530, Year: 2021
Code: SK2590, Year: 2021
Code: TG2530, Year: 2021
Code: SE1020, Year: 2021
Code: ST3550, Year: 2021
Code: SU1535, Year: 2021
Code: TM1080, Year: 2021
Code: SU4590, Year: 2021
Code: SZ5090, Year: 2020
Code: ST6525, Year: 2021
Code: SK0585, Year: 2021
Code: SE9025, Year: 2021
Code: SJ5065, Year: 2021
Code: SX3585, Year: 2021
Code: SW6520, Year: 2021
Code: SX7545, Year: 2021
Code: NZ4060, Year: 2021
Code: SJ6560, Year: 2021
Code: TL0510, Year: 2020
Code: NT9010, Year: 2021
Code: SE1560, Year: 2021
Code: SJ4570, Year: 2021
Code: SU0540, Year: 2021
Code: SS2515, Year: 2021
Code: SJ5035, Year: 2021
Code: SE2075, Year: 2021
Code: ST7040, Year: 2021
Code: SE8540, Year: 2021
Code: SO7090, Year: 2021
Code: NT9500, Year: 2021
Code: SE1070, Year: 2021
Code: NY7020, Year: 2021
Code: SJ4060, Year: 2021
Code: TG2510, Year: 2021
Code: SJ5525, Year: 2021
Code: NY9025, Year: 2021
Code: SS2005, Year: 2021
Code: TQ5575, Year: 2021
Code: SU8035, Year: 2021
Code: SX3095, Year: 2021
Code: TM2095, Year: 2021
Code: SP3500, Year: 2021
Code: SZ6085, Year: 2020
Code: ST5530, Year: 2021
Code: SD5555, Year: 2020
Code: SJ6070, Year: 2021
Code: SX7085, Year: 2021
Code: TL0000, Year: 2020
Code: SU0035, Year: 2021
Code: SD7575, Year: 2021
Code: SJ5540, Year: 2021
Code: TM0580, Year: 2021
Code: SK1085, Year: 2021
Code: SE8525, Year: 2021
Code: SZ4590, Year: 2020
Code: ST7025, Year: 2021
Code: SX5590, Year: 2021
Code: SO5585, Year: 2021
Code: SU3570, Year: 2021
Code: SK1010, Year: 2021
Code: SJ7030, Year: 2021
Code: SK3090, Year: 2021
Code: TG3030, Year: 2021
Code: SE0520, Year: 2021
Code: NZ2545, Year: 2021
Code: SO5095, Year: 2021
Code: ST5045, Year: 2021
Code: SP7595, Year: 2020
Code: SU3060, Year: 2021
Code: SK1500, Year: 2021
Code: TQ1555, Year: 2021
Code: SK3580, Year: 2021
Code: TM0090, Year: 2021
Code: NY7515, Year: 2021
Code: SK1595, Year: 2021
Code: SE8035, Year: 2021
Code: SS7530, Year: 2021
Code: SZ4080, Year: 2020
Code: SE4065, Year: 2021
Code: SX2595, Year: 2021
Code: SK2090, Year: 2021
Code: SD4055, Year: 2020
Code: SX6585, Year: 2021
Code: TL1500, Year: 2020
Code: SE9040, Year: 2021
Code: SO6590, Year: 2021
Code: ST6540, Year: 2021
Code: NT8000, Year: 2021
Code: SE0570, Year: 2021
Code: SE7500, Year: 2021
Code: TQ2050, Year: 2021
Code: SK2005, Year: 2021
Code: TG3010, Year: 2021
Code: NY6520, Year: 2021
Code: NY8525, Year: 2021
Code: SY7580, Year: 2021
Code: SO6080, Year: 2021
Code: NT8510, Year: 2021
Code: SE0060, Year: 2021
Code: SU1040, Year: 2021
Code: TG3500, Year: 2021
Code: SS3015, Year: 2021
Code: SO9550, Year: 2021
Code: SJ6045, Year: 2021
Code: SW7020, Year: 2021
Code: ST4530, Year: 2021
Code: NZ3530, Year: 2021
Code: TL4580, Year: 2021
Code: SX6045, Year: 2021
Code: TL1010, Year: 2020
Code: SX6095, Year: 2021
Code: SJ7060, Year: 2021
Code: SD1570, Year: 2021
Code: SW7515, Year: 2021
Code: SU8090, Year: 2021
Code: SD4070, Year: 2020
Code: SE0555, Year: 2021
Code: SD8595, Year: 2021
Code: SK2020, Year: 2021
Code: SJ9530, Year: 2021
Code: TQ3045, Year: 2021
Code: SS3520, Year: 2021
Code: SD8560, Year: 2021
Code: NY6505, Year: 2021
Code: TQ0030, Year: 2021
Code: SX8080, Year: 2021
Code: SU3040, Year: 2021
Code: SP7545, Year: 2020
Code: SD8085, Year: 2021
Code: SE9575, Year: 2021
Code: SE0545, Year: 2021
Code: NY5540, Year: 2021
Code: SD8070, Year: 2021
Code: TL3570, Year: 2021
Code: NY6015, Year: 2021
Code: SX8590, Year: 2021
Code: SP8575, Year: 2020
Code: SE4550, Year: 2021
Code: SU8580, Year: 2021
Code: SD4560, Year: 2020
Code: SE2035, Year: 2021
Code: SY7070, Year: 2021
Code: NY7030, Year: 2021
Code: SD2565, Year: 2021
Code: SO8095, Year: 2021
Code: SP2595, Year: 2020
Code: NY3510, Year: 2020
Code: SD7065, Year: 2020
Code: SE1530, Year: 2021
Code: SY9595, Year: 2021
Code: SU3555, Year: 2021
Code: TQ1060, Year: 2021
Code: NY6045, Year: 2021
Code: SE0505, Year: 2021
Code: SP1000, Year: 2021
Code: NY5510, Year: 2021
Code: SY9085, Year: 2021
Code: TQ1570, Year: 2021
Code: SE0015, Year: 2021
Code: NY5000, Year: 2021
Code: SE5575, Year: 2020
Code: SO8585, Year: 2021
Code: TQ1045, Year: 2021
Code: NY3000, Year: 2020
Code: TL2020, Year: 2020
Code: SU2525, Year: 2021
Code: SJ8545, Year: 2021
Code: SP9075, Year: 2020
Code: SU9080, Year: 2021
Code: SY6570, Year: 2021
Code: NY6530, Year: 2021
Code: SD5060, Year: 2020
Code: SD9585, Year: 2021
Code: SE8075, Year: 2021
Code: SX4575, Year: 2021
Code: SU2540, Year: 2021
Code: SE1045, Year: 2021
Code: SD9570, Year: 2021
Code: SJ4555, Year: 2021
Code: SD9095, Year: 2021
Code: SJ8030, Year: 2021
Code: SE1055, Year: 2021
Code: SD9060, Year: 2021
Code: TQ2545, Year: 2021
Code: SE2010, Year: 2021
Code: SS2020, Year: 2021
Code: SJ4045, Year: 2021
Code: NY7005, Year: 2021
Code: TQ1530, Year: 2021
Code: SU9590, Year: 2021
Code: SJ6055, Year: 2021
Code: SD5570, Year: 2020
Code: TQ3530, Year: 2021
Code: SO9085, Year: 2021
Code: ST3065, Year: 2021
Code: TQ0545, Year: 2021
Code: SJ5550, Year: 2021
Code: SJ9045, Year: 2021
Code: NY2500, Year: 2020
Code: SP3585, Year: 2020
Code: SU3025, Year: 2021
Code: NY5525, Year: 2021
Code: SE3510, Year: 2020
Code: TQ0070, Year: 2021
Code: SY8585, Year: 2021
Code: SE1515, Year: 2021
Code: TQ2035, Year: 2021
Code: TQ0560, Year: 2021
Code: SE1005, Year: 2021
Code: SO9595, Year: 2021
Code: SP3095, Year: 2020
Code: SU3535, Year: 2021
Code: SE3000, Year: 2020
Code: NY5035, Year: 2021
Code: SE0030, Year: 2021
Code: SD6565, Year: 2020
Code: SU4050, Year: 2021
Code: TM0075, Year: 2021
Code: SP8540, Year: 2020
Code: SJ6585, Year: 2021
Code: SX7595, Year: 2021
Code: SU7585, Year: 2021
Code: SE0095, Year: 2021
Code: NY4015, Year: 2020
Code: TG0010, Year: 2021
Code: SE0585, Year: 2021
Code: SK3075, Year: 2021
Code: NY4505, Year: 2020
Code: TG0500, Year: 2021
Code: SE7055, Year: 2020
Code: SD7590, Year: 2021
Code: SE8520, Year: 2021
Code: SX5575, Year: 2021
Code: TA1025, Year: 2021
Code: SD7565, Year: 2021
Code: SZ4575, Year: 2020
Code: SJ5590, Year: 2021
Code: TQ0595, Year: 2020
Code: TQ4540, Year: 2021
Code: SO7580, Year: 2021
Code: SP9025, Year: 2020
Code: SJ7540, Year: 2021
Code: NZ2550, Year: 2021
Code: TA0540, Year: 2021
Code: SO6575, Year: 2021
Code: ST4525, Year: 2021
Code: SE3055, Year: 2021
Code: SP9535, Year: 2020
Code: SU4545, Year: 2021
Code: SJ5080, Year: 2021
Code: TA2030, Year: 2021
Code: TQ0085, Year: 2020
Code: SK2075, Year: 2021
Code: TL4075, Year: 2021
Code: TG4020, Year: 2021
Code: SU4575, Year: 2021
Code: SE6555, Year: 2020
Code: SE9020, Year: 2021
Code: TA0525, Year: 2021
Code: SZ5075, Year: 2020
Code: TQ4035, Year: 2021
Code: SE1085, Year: 2021

        Code  Year
0     NT6000  2021
1     NT6500  2021
2     NT6505  2021
3     NT7000  2021
4     NT7005  2021
...      ...   ...
6559  TV4095  2019
6560  TV4595  2019
6561  TV5095  2019
6562  TV5595  2019
6563  TV6095  2019

[6564 rows x 2 columns]

In [39]:
clean_files

['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4550_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9035_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG1025_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6005_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5020_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9525_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6050_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG1535_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6515_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SE7580_P_12815_20221209_20221209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ1565_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF8520_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS7515_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ2060_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG0540_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5555_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG2030_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD5010_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4080_P_12539_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD5500_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4590_P_12539_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM2580_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8040_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF9020_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ0065_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD7560_P_12545_20220120_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8025_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP4500_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG0035_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD7015_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8535_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP4010_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG0525_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM3080_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9540_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM3590_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TG1040_P_12753_20221124_20221125.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3530_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK1025_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SU2585_P_12639_20220505_20220505.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK1535_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF9005_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2030_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4025_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD4530_P_12827_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK0540_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4500_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK7065_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4010_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF9515_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ0550_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM0005_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL7515_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4535_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK0035_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5570_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6010_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4040_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5060_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS3505_P_12547_20211122_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6500_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK0525_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ1050_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF8015_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6020_P_12504_20211201_20220119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6565_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3045_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5005_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK1040_P_10682_20220105_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5515_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SX5085_P_12541_20220120_20220120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4065_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF8505_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP3020_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3005_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2570_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS7020_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3030_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3515_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM3575_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD4035_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8510_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8000_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK7090_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5585_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3070_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6520_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2530_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3560_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP2520_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD4050_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5095_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2505_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6590_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL5520_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF7500_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4575_P_12539_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9500_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9010_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3545_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SE8585_P_12815_20221209_20221209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL5505_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS5510_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM5595_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS5000_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM5085_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9540_P_12542_20220112_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL6510_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6505_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS8000_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3055_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6015_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS8510_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP2505_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2520_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL7530_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM4585_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM4095_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SE9085_P_12815_20221209_20221209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP3005_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3020_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9010_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9525_P_12542_20220112_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS7005_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9500_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2555_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9035_P_12542_20220112_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP3515_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3015_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3530_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2560_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP3520_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3505_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD4025_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8500_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8010_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2545_P_12514_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM3075_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK7080_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5595_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3060_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3570_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6020_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD4040_P_12510_20220308_20220308.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5085_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK2515_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM2575_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK6580_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TF7510_P_12752_20221123_20221124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9510_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4075_P_12539_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9000_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9040_P_12542_20220112_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL5515_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS5500_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS5010_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM5095_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SE8085_P_12815_20221209_20221209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6515_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS8010_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS6005_P_10598_20211125_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3555_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS8500_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL7545_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP2515_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL6010_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SE9585_P_12815_20221209_20221209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM4595_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM4085_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SP3015_P_12739_20221208_20221208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9000_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9535_P_12542_20220112_20220112.tif',

In [30]:
# Group by 'Code' and filter groups where the number of unique years is greater than 1
duplicate_codes_df = file_info_df.groupby('Code').filter(lambda x: x['Year'].nunique() > 1)

# Display the result
duplicate_codes_df

        Code  Year
510   NZ2500  2017
511   NZ2500  2023
512   NZ2505  2017
513   NZ2505  2023
514   NZ2510  2017
...      ...   ...
6499  TQ9545  2020
6517  TR0065  2018
6518  TR0065  2019
6533  TR0565  2018
6534  TR0565  2019

[2125 rows x 2 columns]

In [3]:
def generate_tiles_paths(geo_level: str, geo_code: str, imd_lsoa_bua_gdf: gpd.GeoDataFrame) -> tuple:
    """
    Generates tile paths and associated dataframes for a given geographical level and code.
    Parameters:
        geo_level (str): The geographical level (e.g., LSOA, BUA).
        geo_code (str): The geographical code corresponding to the geo_level.
        imd_lsoa_bua_gdf (gpd.GeoDataFrame): A GeoDataFrame containing geographical data.
    Returns:
        tuple: A tuple containing the following elements:
            - subgeo_filt_gdf (gpd.GeoDataFrame): A filtered GeoDataFrame for the specified geo_level and geo_code.
            - geo_boundary_gdf (gpd.GeoDataFrame): A dissolved GeoDataFrame containing the boundary geometry for the specified geo_level.
            - geo_selected_vom_tiles_df (pd.DataFrame): A DataFrame containing selected VOM tiles for the specified geo_code.
            - tif_paths_df (pd.DataFrame): A DataFrame containing paths to .tif files, along with their year, tile name, and file type.
    """

    logging.debug("Generating tile paths")

    subgeo_filt_gdf = imd_lsoa_bua_gdf.copy()[imd_lsoa_bua_gdf[geo_level].isin([geo_code])].reset_index(drop=True)

    geo_vom_tiles_path = vom_lad_dir / f"VOM_tiles_{geo_code}.csv"
    geo_vom_tiles_df = pd.read_csv(geo_vom_tiles_path).sort_values(['TILE_NAME', 'year'], ascending=[True, False])
    geo_selected_vom_tiles_df = geo_vom_tiles_df.groupby(['TILE_NAME']).first().reset_index()
    
    return subgeo_filt_gdf, geo_vom_tiles_df, geo_selected_vom_tiles_df

In [5]:
imd_lsoa_bua_gdf = gpd.read_file(imd_lsoa_bua_boundaries_path).sort_values(by=geo_level)
geo_level_codes = imd_lsoa_bua_gdf[geo_level].unique()

In [6]:

geo_level_codes = imd_lsoa_bua_gdf[geo_level].unique()
chm_tiles_dict = {}
geo_code_errors = {}
for geo_code in tqdm(geo_level_codes):
    try:
        _, geo_vom_tiles_df, geo_selected_vom_tiles_df = generate_tiles_paths(geo_level, geo_code, imd_lsoa_bua_gdf)
        selected_chm_path_lst = select_chm_files(geo_vom_tiles_df, geo_selected_vom_tiles_df, tif_paths_df)

        chm_tiles_dict[geo_code] = [str(path) for path in selected_chm_path_lst]
    except Exception as e:
        geo_code_errors[geo_code] = type(e).__name__

100%|██████████| 309/309 [00:23<00:00, 12.98it/s]

In [7]:
chm_tiles_dict

{'E06000001': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ3525_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4525_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4025_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4535_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4035_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4530_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4030_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ5025_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ5035_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ5030_P_12516_20211120_20211120.tif'],
 'E06000002': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4515_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4510_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4520_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5015_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5510_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5010_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5020_P_12742_20230118_20230118.tif'],
 'E06000003': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5515_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5015_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5510_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5010_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5525_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ5025_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5520_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5020_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ6515_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ6015_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ6510_P_10731_20171209_20180426.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ6010_P_10731_20171209_20180426.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ6025_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ6520_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ6020_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_NZ7515_P_10748_20201104_20201104.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ7015_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ7010_P_12742_20230118_20230118.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ7020_P_12742_20230118_20230118.tif'],
 'E06000004': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3505_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3515_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3510_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ3525_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3520_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4505_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4005_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4515_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4015_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4510_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4010_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4525_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ4025_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4520_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4020_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ5025_P_12516_20211120_20211120.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ5020_P_12742_20230118_20230118.tif'],
 'E06000005': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ1515_P_10689_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ1520_P_10689_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ2505_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ2515_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ2015_P_10689_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ2510_P_10711_20171208_20180324.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ2010_P_10689_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ2520_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ2020_P_10689_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3505_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3005_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3515_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3015_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3510_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3010_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3520_P_12741_20230117_20230117.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3020_P_12741_20230117_20230117.tif'],
 'E06000006': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ4575_P_10621_20190211_20190211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ4585_P_10621_20190211_20190211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ4580_P_10621_20190211_20190211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ4080_P_10621_20190211_20190211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SJ5575_P_11779_20200205_20200205.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SJ5075_P_11779_20200205_20200205.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5585_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5085_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5580_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5080_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6080_P_11996_20210211_20210211.tif'],
 'E06000007': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5585_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5085_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5580_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5080_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ5595_P_11647_20190423_20190423.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5590_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5090_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6585_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6085_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6580_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6080_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ6595_P_11647_20190423_20190423.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ6095_P_11647_20190423_20190423.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6590_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ6090_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ7085_P_11996_20210211_20210211.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ7090_P_11996_20210211_20210211.tif'],
 'E06000008': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6515_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6015_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6510_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SD6525_P_10642_20180126_20180324.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SD6025_P_10642_20180126_20180324.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6520_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD6020_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SD6530_P_10642_20180126_20180324.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SD7515_P_10662_20190214_20190329.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD7015_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SD7510_P_10662_20190214_20190329.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD7010_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SD7025_P_10642_20180126_20180324.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SD7520_P_10662_20190214_20190329.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD7020_P_12504_20211201_20220119.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SD7030_P_10642_20180126_20180324.tif'],
 'E06000009': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3035_P_12510_20220308_20220308.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3530_P_12510_20220308_20220308.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3030_P_12510_20220308_20220308.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SD3040_P_12510_20220308_20220308.tif'],
 'E06000010': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA0525_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA0025_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA0535_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA0530_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA0030_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA1525_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA1025_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA1035_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA1530_P_12524_20211124_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TA1030_P_12524_20211124_20211215.tif'],
 'E06000011': ['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE5515_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE5520_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6515_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6015_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6525_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6520_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6020_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6535_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6545_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE6540_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7515_P_12522_20211215_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7015_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7525_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7025_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE7520_P_10744_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7020_P_10727_20200322_20200323.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7535_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7035_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7530_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7030_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE7545_P_10745_20181209_20181210.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7045_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7540_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE7040_P_10728_20201123_20201123.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE7555_P_10746_20181209_20181209.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7055_P_10729_20201119_20210406.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE7550_P_10746_20181209_20181209.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7050_P_10729_20201119_20210406.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8015_P_12522_20211215_20211215.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8525_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8025_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE8520_P_10744_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE8020_P_10744_20181114_20181204.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8535_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8035_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8530_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8030_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8545_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8045_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8540_P_12523_20211216_20211222.tif',
  '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8040_P_12523_20211216_20211222.tif',

In [9]:
vom_lad_dir / "LAD_CHM_tiles_paths.json"

PosixPath('/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/LADs/LAD_CHM_tiles_paths.json')

In [38]:
len(unique_paths)

5402

In [37]:
unique_paths = set()
for paths in chm_tiles_dict.values():
    unique_paths.update(paths)

unique_paths = list(unique_paths)
unique_paths

['/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST0030_P_10606_20190102_20190117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM1555_P_12748_20230208_20230208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_ST7505_P_10650_20171218_20180224.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_NY9585_P_10669_20191231_20200318.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE1000_P_10685_20200323_20200323.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SS7025_P_10599_20200118_20200119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE1060_P_10687_20210412_20210413.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ2550_P_12517_20211124_20211124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SW9040_P_12735_20230206_20230206.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SW5035_P_10587_20200118_20200119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_ST9510_P_10650_20171218_20180224.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SO7515_P_10654_20190225_20190226.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SU8075_P_12755_20230402_20230403.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SZ5080_P_10714_20201201_20210210.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_NY9530_P_11654_20191119_20191119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TQ5500_P_10779_20190104_20190120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TQ8540_P_11894_20200117_20200118.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5525_P_10638_20210409_20210409.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SP3545_P_10700_20190328_20190328.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SD9500_P_11777_20200318_20200321.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE0035_P_10686_20210222_20210316.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SK0005_P_10681_20210213_20210227.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM4090_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TG4520_P_12529_20211216_20211216.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SX0565_P_10590_20171219_20180418.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TR0015_P_11893_20200119_20200201.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SO3050_P_11997_20210211_20210227.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SX3060_P_10592_20200119_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ3075_P_10692_20181210_20181210.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SD9565_P_10664_20210507_20210507.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SU7545_P_12241_20210419_20210419.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_ST4035_P_12536_20211122_20211122.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TA1075_P_10764_20201103_20201103.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SU3025_P_10696_20210404_20210405.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TF0090_P_10760_20190320_20190405.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ7500_P_10658_20191119_20191203.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SU1565_P_10675_20181210_20190109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL7535_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TL8065_P_12747_20230111_20230209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SX6080_P_10597_20210411_20210411.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SE3585_P_10710_20191118_20191119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TQ1000_P_10749_20190108_20190117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TF7010_P_10787_20181113_20181117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ8505_P_10658_20191119_20191203.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SU6070_P_10717_20190123_20190325.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SK8500_P_10740_20201122_20201123.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TM1075_P_12527_20211117_20211202.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SP3590_P_10702_20201215_20210213.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE8510_P_12522_20211215_20211215.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TF2500_P_10773_20201119_20201122.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SX1080_P_11828_20191202_20191202.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TQ2530_P_10766_20210218_20210218.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TM3035_P_10807_20191211_20200107.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SU5550_P_10717_20190123_20190325.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NY6035_P_10646_20210301_20210302.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SE8570_P_10746_20181209_20181209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL7525_P_12507_20220121_20220121.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NY3515_P_10625_20201130_20210112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TA3005_P_10777_20201215_20201215.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SP3575_P_10702_20201215_20210213.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SU2030_P_11641_20190425_20190429.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SE3035_P_10708_20191230_20191230.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM2570_P_12751_20221124_20230111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST9555_P_10652_20181210_20190109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SU0080_P_11466_20190127_20190127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SP1520_P_12738_20230206_20230207.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9510_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE7095_P_10730_20201104_20210406.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK5080_P_12521_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE5540_P_10728_20201123_20201123.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ2590_P_10621_20190211_20190211.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE2020_P_11993_20210225_20210406.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE5520_P_10727_20200322_20200323.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4080_P_12539_20220104_20220104.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_NZ0540_P_11465_20190108_20190215.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK3500_P_12513_20220105_20220112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SP9060_P_10738_20200129_20200306.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SE5010_P_10727_20200322_20200323.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST7570_P_10652_20181210_20190109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SD5565_P_10643_20201130_20210112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SO2085_P_10617_20200120_20200205.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST1025_P_10606_20190102_20190117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NZ3050_P_12517_20211124_20211124.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SS9000_P_10602_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_NZ0045_P_11465_20190108_20190215.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SK8530_P_10741_20191202_20191209.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TF0030_P_10758_20190329_20190329.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TQ6585_P_10782_20181222_20190108.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM0565_P_12748_20230208_20230208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TF1090_P_10760_20190320_20190405.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TL7065_P_12746_20230210_20230210.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SP5050_P_10721_20181204_20181204.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ3010_P_12741_20230117_20230117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SP0065_P_10679_20201201_20201201.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM2060_P_12748_20230208_20230208.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SE7585_P_13024_20221209_20230224.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE3505_P_10707_20201220_20210330.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TQ6595_P_10782_20181222_20190108.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK4055_P_12515_20220104_20220105.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NZ0520_P_10689_20181114_20181204.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SE8085_P_13024_20221209_20230224.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SP9095_P_10739_20201215_20210102.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SO8585_P_10657_20210210_20210211.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NY2520_P_10625_20201130_20210112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL5520_P_12509_20211221_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SW9075_P_10589_20191202_20191202.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9500_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SP9035_P_10737_20201215_20210117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TQ3065_P_10767_20180207_20180207.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NY6545_P_10646_20210301_20210302.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST0045_P_10606_20190102_20190117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SU6020_P_10715_20200120_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TQ7075_P_12505_20211221_20211221.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SJ4510_P_10618_20200205_20200206.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SE2590_P_10710_20191118_20191119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TQ4555_P_10767_20180207_20180207.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TL0060_P_12743_20230403_20230403.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SD8075_P_10665_20210416_20210418.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK7020_P_12518_20220112_20220113.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_ST7025_P_10630_20210210_20210212.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE0590_P_10688_20210112_20210112.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SJ5530_P_10638_20210409_20210409.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_NY7035_P_10646_20210301_20210302.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SX8070_P_10600_20200120_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SO7585_P_10657_20210210_20210211.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SU5015_P_10715_20200120_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_ST5010_P_10629_20201201_20201201.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TQ6020_P_10779_20190104_20190120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SX9055_P_10600_20200120_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SS7545_P_10603_20210404_20210404.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SE4570_P_10709_20210406_20210412.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_NZ4510_P_12741_20230117_20230117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TL2055_P_12743_20230403_20230403.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SX4585_P_10593_20210415_20210415.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TL1025_P_10754_20200306_20200316.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_SK7050_P_12520_20220117_20220117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_NZ1550_P_12512_20211124_20220111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SD8000_P_11777_20200318_20200321.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SD7505_P_11777_20200318_20200321.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM4060_P_12751_20221124_20230111.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_SW8530_P_12735_20230206_20230206.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SK5540_P_10724_20180125_20180130.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SO6580_P_10636_20210228_20210404.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SY9080_P_11991_20210226_20210226.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_NY8060_P_11469_20190308_20190323.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_SU1035_P_11780_20210404_20210404.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SP6050_P_10721_20181204_20181204.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TG4020_P_12529_20211216_20211216.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_TF4565_P_10775_20190329_20190329.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SK8005_P_10740_20201122_20201123.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_NU0530_P_10694_20181115_20181115.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_ST9070_P_10652_20181210_20190109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL9000_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_ST7015_P_10629_20201201_20201201.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TQ3070_P_10767_20180207_20180207.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_NY4555_P_10627_20200207_20200318.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SZ6095_P_10715_20200120_20200120.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TF6015_P_10787_20181113_20181117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TM2585_P_12528_20220107_20220109.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TQ4030_P_10766_20210218_20210218.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_SP4550_P_10701_20181217_20181217.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SJ7020_P_10637_20191119_20191203.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2019/VOM_SE3595_P_10710_20191118_20191119.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SK0050_P_10683_20191203_20200118.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TL7595_P_10795_20181117_20181117.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_TM3045_P_10807_20191211_20200107.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TG5010_P_12529_20211216_20211216.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2022/VOM_TL8010_P_12506_20220127_20220127.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2021/VOM_TL2010_P_10753_20201212_20210227.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2020/VOM_SO4560_P_10616_20200322_20200322.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2023/VOM_TM2040_P_12749_20230109_20230219.tif',
 '/maps/acz25/phd-thesis-data/input/raster/Defra/VOM/unzipped_tiles/2018/VOM_TL9075_P_10795_20181117_20181117.tif',

In [40]:
# Define the path to save the JSON file
json_output_path = vom_lad_dir / "LAD_CHM_tiles_paths_full.json"

# Dump the dictionary to a JSON file
with open(json_output_path, 'w') as json_file:
    json.dump(clean_files, json_file)